# .goreleaser.yml for GoReleaser configuration

before:
  hooks:
    - go mod tidy

builds:
  - goos: windows
    goarch: amd64
  - goos: linux
    goarch: amd64
  - goos: darwin
    goarch: amd64

archive:
  format: tar.gz

release:
  github:
    owner: YourGitHubUsername
    name: chat-hub-golang
  draft: true
  checksum: true
  file: dist/chat-hub-golang_{{ .Version }}_{{ .Arch }}.{{ .Os }}.tar.gz
  body: "{{ .ReleaseNotes }}"
